"""Registered daily workflow definitions."""

from .batch1 import (
    BATTLE_PASS_REWARD_DAILY_DEFINITION,
    COLLECTION_DEPLOYMENT_DAILY_DEFINITION,
    DAILY_TASK_REWARD_CLAIM_DAILY_DEFINITION,
    FREE_APPRAISAL_DAILY_DEFINITION,
    MAIL_REWARD_DAILY_DEFINITION,
    SHOP_FREE_GIFT_DAILY_DEFINITION,
    TRIAL_SWORD_DAILY_DEFINITION,
    WEEKLY_FREE_GIFT_MONDAY_DEFINITION,
)
from .batch23 import (
    BUY_TEA_DAILY_DEFINITION,
    DUNGEON_SWEEP_DAILY_DEFINITION,
    EAT_STAMINA_FOOD_DAILY_DEFINITION,
    HERO_DISPATCH_DAILY_DEFINITION,
    MARTIAL_STUDY_BREAKTHROUGH_DAILY_DEFINITION,
    RING_CHALLENGE_DAILY_DEFINITION,
    SHADOW_RUINS_DAILY_DEFINITION,
    SPEND_CONDENSATE_DAILY_DEFINITION,
)
from .jianlin_resource_condensate_stamina_daily import (
    JIANLIN_RESOURCE_CONDENSATE_STAMINA_DAILY_DEFINITION,
)

__all__ = [
    "BATTLE_PASS_REWARD_DAILY_DEFINITION",
    "BUY_TEA_DAILY_DEFINITION",
    "COLLECTION_DEPLOYMENT_DAILY_DEFINITION",
    "DUNGEON_SWEEP_DAILY_DEFINITION",
    "DAILY_TASK_REWARD_CLAIM_DAILY_DEFINITION",
    "EAT_STAMINA_FOOD_DAILY_DEFINITION",
    "FREE_APPRAISAL_DAILY_DEFINITION",
    "HERO_DISPATCH_DAILY_DEFINITION",
    "JIANLIN_RESOURCE_CONDENSATE_STAMINA_DAILY_DEFINITION",
    "MAIL_REWARD_DAILY_DEFINITION",
    "SHOP_FREE_GIFT_DAILY_DEFINITION",
    "MARTIAL_STUDY_BREAKTHROUGH_DAILY_DEFINITION",
    "RING_CHALLENGE_DAILY_DEFINITION",
    "SHADOW_RUINS_DAILY_DEFINITION",
    "SPEND_CONDENSATE_DAILY_DEFINITION",
    "TRIAL_SWORD_DAILY_DEFINITION",
    "WEEKLY_FREE_GIFT_MONDAY_DEFINITION",
]
