from .batch23 import MARTIAL_STUDY_BREAKTHROUGH_DAILY_DEFINITION

TRANSITIONS = MARTIAL_STUDY_BREAKTHROUGH_DAILY_DEFINITION.transitions

__all__ = ["MARTIAL_STUDY_BREAKTHROUGH_DAILY_DEFINITION", "TRANSITIONS"]
