from enum import StrEnum


class ErrorCode(StrEnum):
    """Stable machine-readable failure codes for an MJA run."""

    PERMISSION_SCREEN_CAPTURE = "PERMISSION_SCREEN_CAPTURE"
    PERMISSION_ACCESSIBILITY = "PERMISSION_ACCESSIBILITY"
    APP_LAUNCH_TIMEOUT = "APP_LAUNCH_TIMEOUT"
    WINDOW_NOT_FOUND = "WINDOW_NOT_FOUND"
    WINDOW_RESIZE_FAILED = "WINDOW_RESIZE_FAILED"
    DISPLAY_CONTRACT_MISMATCH = "DISPLAY_CONTRACT_MISMATCH"
    ANDROID_SDK_UNAVAILABLE = "ANDROID_SDK_UNAVAILABLE"
    ANDROID_AVD_FAILED = "ANDROID_AVD_FAILED"
    ANDROID_EMULATOR_CONTRACT_FAILED = "ANDROID_EMULATOR_CONTRACT_FAILED"
    ADB_DEVICE_FAILED = "ADB_DEVICE_FAILED"
    ANDROID_GAME_NOT_FOUND = "ANDROID_GAME_NOT_FOUND"
    ANDROID_LOGIN_REQUIRED = "ANDROID_LOGIN_REQUIRED"
    ANDROID_INSTALL_FAILED = "ANDROID_INSTALL_FAILED"
    ANDROID_RUN_ALREADY_ACTIVE = "ANDROID_RUN_ALREADY_ACTIVE"
    ANDROID_STORAGE_LOW = "ANDROID_STORAGE_LOW"
    ANDROID_NETWORK_UNAVAILABLE = "ANDROID_NETWORK_UNAVAILABLE"
    ANDROID_MEMORY_LOW = "ANDROID_MEMORY_LOW"
    ANDROID_SELINUX_INCOMPATIBLE = "ANDROID_SELINUX_INCOMPATIBLE"
    ANDROID_SYSTEM_UI_NOT_RESPONDING = "ANDROID_SYSTEM_UI_NOT_RESPONDING"
    ANDROID_SHARED_RUNTIME_FAILURE = "ANDROID_SHARED_RUNTIME_FAILURE"
    ANDROID_GAME_PROCESS_DIED = "ANDROID_GAME_PROCESS_DIED"
    ANDROID_GAME_NOT_FOREGROUND = "ANDROID_GAME_NOT_FOREGROUND"
    WORKFLOW_TIMEOUT = "WORKFLOW_TIMEOUT"
    WORKFLOW_STEP_CAP = "WORKFLOW_STEP_CAP"
    WORKFLOW_POSTCONDITION_MISSING = "WORKFLOW_POSTCONDITION_MISSING"
    WORKFLOW_DRIVER_FAILED = "WORKFLOW_DRIVER_FAILED"
    CONTROLLER_CONNECT_FAILED = "CONTROLLER_CONNECT_FAILED"
    CONTROLLER_PROBE_FAILED = "CONTROLLER_PROBE_FAILED"
    HOME_RECOGNITION_TIMEOUT = "HOME_RECOGNITION_TIMEOUT"
    MAIL_OPEN_TIMEOUT = "MAIL_OPEN_TIMEOUT"
    HOME_RETURN_TIMEOUT = "HOME_RETURN_TIMEOUT"
    TASK_BOUNDARY_RETURN_FAILED = "TASK_BOUNDARY_RETURN_FAILED"
    TASK_BOUNDARY_VERIFY_FAILED = "TASK_BOUNDARY_VERIFY_FAILED"
    WINDOW_RESTORE_FAILED = "WINDOW_RESTORE_FAILED"


class MJAError(RuntimeError):
    """An expected, diagnosable failure in an MJA run."""

    def __init__(self, code: ErrorCode, message: str) -> None:
        super().__init__(message)
        self.code = code

    def as_dict(self) -> dict[str, str]:
        return {"code": self.code.value, "message": str(self)}
